dist: trusty
language: python
python:
    - "3.6"
script:
    - pytest
sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    
    - sudo apt update

    - sudo apt-get install software-properties-common
    
    - sudo apt-get install -y python3-pyqt5
    - sudo apt-get install -y python3-twisted 
    - sudo apt-get install -y python3-treq
    - sudo apt-get install -y python3-protobuf
    - sudo apt-get install -y protobuf-compiler 
    - sudo apt-get install -y python3-protobuf
    - sudo apt-get install -y python3-cryptography 
    - sudo apt-get install -y python3-sqlalchemy 
    - sudo apt-get install -y python3-toml 
    - sudo apt-get install -y python3-boto3
    
    - pip3 search ipfsapi
    - pip3 search qt5reactor
    - pip3 search web3
    - echo "----------------------------"
    - sudo sh install-deps.sh
    - pip3 install web3==4.1.0
    - pip3 install eth-keyfile