dist: trusty
language: python
python:
    - "3.6"
script:
    - pytest
sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo mv /etc/apt/source.list /etc/apt/source.list.cp
    - sudo cp source.list /etc/apt/source.list
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    
    - sudo apt update
    - sudo apt upgrade
    - sudo apt-get install software-properties-common
    
    - sudo apt-get install -y python3-pyqt5
    - sudo apt-get install -y python3-twisted python3-treq
    - sudo apt-get install -y python3-protobuf
    - sudo apt-get install -y protobuf-compiler python3-protobuf
    - sudo apt-get install -y python3-cryptography python3-sqlalchemy python3-toml python3-boto3
    
    - pip3 search ipfsapi
    - pip3 search qt5reactor
    - pip3 search web3
    - echo "----------------------------"
    - sudo sh install-deps.sh
    - pip3 install web3==4.1.0
    - pip3 install eth-keyfile