dist: trusty
language: python
python:
    - "3.6"
script:
    - python test_core_logic.py
sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    
    - sudo apt update

    - sudo apt-get install software-properties-common
       
    - sudo sh install-deps.sh