dist: trusty
language: python
python:
    - "3.6"
script:
    - python test/test_core_logic.py
sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    
    - sudo apt update

    - sudo apt-get install software-properties-common
       
    
    - pip3 search ipfsapi
    - pip3 search qt5reactor
    - pip3 search web3
    - echo "----------------------------"
    - sudo sh install-deps.sh
    - pip3 install web3==4.1.0
    - pip3 install eth-keyfile
    
    - pip3 install pyqt5
    - pip3 install twisted
    - pip3 install treq
    - pip3 install protobuf
    - pip3 install cryptography
    - pip3 install sqlalchemy
    - pip3 install toml
    - pip3 install boto3
    