dist: trusty
language: python
python:
    - "3.6"
script:
    - python test_core_logic.py
sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo apt update
    - sudo apt-get install software-properties-common
    
    - echo "-------market----------"
    - pip3 install djangorestframework==3.7.3
    - pip3 install django==2.0.3
    - pip3 install psycopg2
    - pip3 install toml==0.9.4
    - pip3 install django-rest-elasticsearch==0.4
    - echo "-------wallet-----------"
    
    - pip3 install ipfsapi
    - pip3 install qt5reactor
    - pip3 install web3==4.1.0
    - echo "----------------------------"
    - pip3 install eth-keyfile
    
    - pip3 install pyqt5
    - pip3 install twisted
    - pip3 install treq
    - pip3 install protobuf
    - pip3 install cryptography
    - pip3 install sqlalchemy
    - pip3 install toml
    - pip3 install boto3
    