dist: trusty
language: python
python:
    - "3.6"
script:
    - pytest
# sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    
    - sudo apt-get update
    - sudo sh install-deps.sh