dist: trusty
language: python
python:
    - "3.6"
#script:
#    - pytest
# sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    
    - sudo apt-get update
    - pip3 search ipfsapi
    - pip3 search eth-keyfile
    - pip3 search qt5reactor
    - pip3 search web3
    - echo "----------------------------"
    - sudo sh install-deps.sh
    - pip3 install web3==4.1.0