dist: trusty
language: python
python:
    - "3.6"
script:
    - pytest
# sudo: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
install:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    
    - sudo apt-get update
    - sudo apt install -y python3-pyqt5
    - sudo apt install -y python3-pyqt5
    - sudo apt install -y python3-twisted python3-treq
    - sudo apt install -y python3-protobuf
    - sudo apt install -y protobuf-compiler python3-protobuf
    - sudo apt install -y python3-cryptography python3-sqlalchemy python3-toml python3-boto3
    
    - echo "----------------------------"
    - sudo sh install-deps.sh
    - pip3 install web3==4.1.0
    - pip3 install eth-keyfile