image: ubuntu
stack: python 3.6,pip 3


before_build:
    - sudo add-apt-repository main
    - sudo add-apt-repository universe
    - sudo add-apt-repository restricted
    - sudo add-apt-repository multiverse
    - sudo apt-get update

build_script:
    - sudo sh install-deps.sh

after_build:
    - pytest